#!/bin/bash

exec xautolock \
        -time 10 \
        -bell 0 \
        -detectsleep \
        -locker ~/.i3/blurred-lock \
        -notify 5 \
        -notifier "notify-send -t 1000 -i ~/.i3/lock-icon.png 'Locking Screen...'"
