#!/bin/bash

echo ""

if [[ $BLOCK_BUTTON == '1' ]]; then
        notify-send -i ~/.i3/lock-icon.png "Disabling lock and screensaver" -t 3000
        xautolock -disable
        xset s off
        xset -dpms
elif [[ $BLOCK_BUTTON == '3' ]]; then
        notify-send -i ~/.i3/lock-icon.png "Enabling lock and screensaver" -t 3000
        xautolock -enable
        xset s on
        xset +dpms
fi
