#!/bin/bash

# Add a button to toggle play and pause on Spotify if it's running
if [[ $(ps -U root -u root -N | grep -Fo 'spotify') == *spotify* ]]; then
        echo ""
        echo ""
        echo "#99CC99"
        if [[ $BLOCK_BUTTON == '1' ]]; then
                playerctl -p spotify play-pause
        fi
        #if [[ $STATUS == 'Paused' ]]; then
        #        echo ""
        #        echo ""
        #        echo "#99CC99"
        #        if [[ $BLOCK_BUTTON == '1' ]]; then
        #                playerctl -p spotify play-pause
        #        fi
        #fi
        #if [[ $STATUS == 'Playing' ]]; then
        #        echo ""
        #        echo ""
        #        echo "#99CC99"
        #        if [[ $BLOCK_BUTTON == '1' ]]; then
        #                playerctl -p spotify play-pause
        #        fi
        #fi
fi
