#!/bin/bash

# Create a button to skip to next track in Spotify.

if [[ $(ps -U root -u root -N | grep -Fo 'spotify') == *spotify* ]]; then
        echo ""
        echo ""
        echo "#99CC99"
        if [[ $BLOCK_BUTTON == '1' ]]; then
                playerctl -p spotify next
        fi
fi
