#!/bin/bash

# Toggle the screen lock on and off by clicking the icon. For some reason the
# xautolock command has no status option. So use that it starts on at start up
# to start it as on.

toggleLock () {
        if [[ "$STATE" == "on" ]]; then
                xautolock -disable
                BUTTON=""
                STATE="off"
        elif [[ "$STATE" == "off" ]]; then
                xautolock -enable
                BUTTON=""
                STATE="on"
        fi
}

case $BLOCK_BUTTON in
  1) toggleLock
esac

echo $BUTTON"-"$STATE

