#!/bin/bash

if ! [[ "$(hostname)" == "m73" ]]; then
        exit 0
else
        echo ""
        if [[ $BLOCK_BUTTON == '1' ]]; then
                urxvt
        fi
        if [[ $BLOCK_BUTTON == '3' ]]; then
                urxvt
        fi
fi

