#!/bin/sh
wlan_state="$(cat /sys/class/net/wlan0/operstate)"

if [ "$wlan_state" = "up" ]; then
        echo ""
        echo "j"
        echo "#99CC99"
        exit 0
fi
if [ "$wlan_state" = "down" ]; then
        echo ""
        echo ""
        echo "#F2777A"
        exit 0
fi
if [ "$wlan_state" = "dormant" ]; then
        echo ""
        echo ""
        echo "#F299157"
        exit 0
fi
