#!/bin/bash

# Show battery percentage and status in i3bar.
# Change the color with the percentage and display low battery notifications.
# Clicking on the icon shows amount of time remaining/time until charged.

POWER=$(acpi -b)
if [[ "$POWER" == "" ]]; then
        exit 1
fi
STATE=$(echo $POWER | cut -d : -f 2 | cut -d , -f 1 | tr '[:upper:]' '[:lower:]' \
        | sed 's/[[:space:]]//g')
PERCENTAGE=$(echo $POWER | grep -o '[^ ]*%' | grep -o '[0-9]*')
REMAINING=$(acpi -b | cut -d % -f 2 | cut -d , -f 2)

if [[ "$STATE" == "charging" ]]; then
        COLOR=""
        if [[ "$PERCENTAGE" -lt "15" ]]; then
                SYMBOL=""
        elif [[ "$PERCENTAGE" -lt "30" ]]; then
                SYMBOL=""
        elif [[ "$PERCENTAGE" -lt "45" ]]; then
                SYMBOL=""
        elif [[ "$PERCENTAGE" -lt "60" ]]; then
                SYMBOL=""
        elif [[ "$PERCENTAGE" -lt "75" ]]; then
                SYMBOL=""
        elif [[ "$PERCENTAGE" -lt "97" ]]; then
                SYMBOL=""
        else
                SYMBOL=""
        fi
elif [[ "$STATE" == "discharging" ]]; then
        if [[ "$PERCENTAGE" -lt "10" ]]; then
                SYMBOL=""
                COLOR=`cat ~/.colors | grep base08 | cut -d = -f 2`
                notify-send -t 1000 -i ~/.i3/icons/low-battery.png 'Battery Low'
        elif [[ "$PERCENTAGE" -lt "20" ]]; then
                SYMBOL=""
                COLOR=`cat ~/.colors | grep base09 | cut -d = -f 2`
        elif [[ "$PERCENTAGE" -lt "30" ]]; then
                SYMBOL=""
                COLOR=`cat ~/.colors | grep base0A | cut -d = -f 2`
        elif [[ "$PERCENTAGE" -lt "40" ]]; then
                SYMBOL=""
                COLOR=`cat ~/.colors | grep base0B | cut -d = -f 2`
        elif [[ "$PERCENTAGE" -lt "50" ]]; then
                SYMBOL=""
        elif [[ "$PERCENTAGE" -lt "60" ]]; then
                SYMBOL=""
        elif [[ "$PERCENTAGE" -lt "70" ]]; then
                SYMBOL=""
        elif [[ "$PERCENTAGE" -lt "80" ]]; then
                SYMBOL=""
        elif [[ "$PERCENTAGE" -lt "90" ]]; then
                SYMBOL=""
        else
                SYMBOL=""
        fi
elif [[ "$STATE" == "full" ]] | [[ "$STATE" == "unknown" ]]; then
        SYMBOL=""
        COLOR=""
else
        SYMBOL=""
        COLOR=""
fi

echo $SYMBOL
echo $SYMBOL
echo $COLOR

if [[ $BLOCK_BUTTON == '1' ]]; then
        notify-send "Battery: $PERCENTAGE%" -t 2000 \
                -i /usr/share/icons/Numix-Circle/scalable/apps/battery.svg
fi

if [[ $BLOCK_BUTTON == '3' ]]; then
        notify-send "$REMAINING" -t 2000 \
                -i /usr/share/icons/Numix-Circle/scalable/apps/battery.svg
fi
