#!/bin/bash

# Create a blurred image with a lock symbol in the middle for i3lock. If using
# multimonitor, the lock symbol will show up on each screen. This assumes that
# the internal display (laptop screen) is to the right of the external display
# when using multi-monitor. Also pauses music and mutes volume.

IMAGE=~/.blur.png
TEXT=~/.text.png
LEFT=~/.blur-0.png
RIGHT=~/.blur-1.png
LOCK_ICON=~/.config/i3/icons/keys.png
NUM_ACTIVE_SCREENS=`xrandr -q | grep ' connected' | grep '[0-9]x[0-9]' | wc -l`

# Pause spotify and mopidy if either are running:
playerctl -p spotify pause
MPC_STATE=$(mpc | sed -n '2p' | cut -d "[" -f2 | cut -d "]" -f1)
if [[ $MPC_STATE == "playing" ]]; then
        mpc pause
fi
# Mute volume in case anything else is on:
amixer -q sset Master mute

MESSAGE='Enter password'

if [[ "$NUM_ACTIVE_SCREENS" == "2" ]]; then
        # Screenshot:
        scrot $IMAGE
        # Pixelate:
        mogrify -scale 10% -scale 1000% $IMAGE
        # convert $IMAGE -blur 0x8 $IMAGE
        # Get the monitor resolution of both displays:
        SCREEN1_RES=`xrandr | grep \* | cut -d' ' -f4 | sed -n '1p'`
        SCREEN2_RES=`xrandr | grep \* | cut -d' ' -f4 | sed -n '2p'`
        # Get the width of the displays:
        SCREEN1_WIDTH=`echo $SCREEN1_RES | cut -d x -f 1`
        SCREEN2_WIDTH=`echo $SCREEN2_RES | cut -d x -f 1`
        # Extract the left display from the screenshot:
        convert $IMAGE -crop $SCREEN1_RES+0+0 $LEFT
        # Extract the right display from the screenshot:
        convert $IMAGE -crop $SCREEN1_RES+$SCREEN1_WIDTH+0 $RIGHT
        # Add the lock symbol to the center of each display:
        convert $LEFT $LOCK_ICON -gravity center -composite -matte $LEFT
        convert $RIGHT $LOCK_ICON -gravity center -composite -matte $RIGHT
        # Put the two images together:
        convert $LEFT $RIGHT +append $IMAGE
else
        # With only 1 connected screen, just screenshot, pixelate and add lock
        # to the center of the image (also add unlock text):
        scrot $IMAGE
        # mogrify -scale 5% -scale 2000% $IMAGE
        convert $IMAGE -blur 0x8 $IMAGE
        convert $IMAGE $LOCK_ICON -gravity center -composite -matte $IMAGE

fi

i3lock -u -i $IMAGE
