#!/bin/bash
echo $(date "+%-d. %b %H:%M")
if [[ $BLOCK_BUTTON == '1' ]]; then
        urxvt
elif [[ $BLOCK_BUTTON == '3' ]]; then
        notify-send "$(date "+%A, %e. %B, %H:%M")" -t 1000 \
                -i /usr/share/icons/Numix-Circle/48/apps/gnome-clocks.svg
fi
