#!/bin/bash

# Show the CPU temperature in red if it's hotter than 70 degrees celcius.

TEMP=$(echo -e `acpi -t | grep -oP '\d+\\d+'`)
if [[ $((TEMP)) -gt 70 ]]; then
        COLOR=`cat ~/.colors | grep base08 | cut -d = -f 2`
        echo ""$TEMP "°C"
        echo ""$TEMP "°C"
        echo "$COLOR"
        if [[ $BLOCK_BUTTON == '1' ]]; then
                notify-send "`echo $(acpi -t)`" -i /usr/share/icons/Numix-Circle/scalable/apps/setroubleshoot_icon.svg
        fi
fi

