#!/bin/bash

# Show the CPU temperature in red if it's hotter than 70 degrees celcius.t

TEMP=$(echo -e `acpi -t | grep -oP '\d+\\d+'`)
if [[ $((TEMP)) -gt 70 ]]; then
        echo ""$TEMP "°C"
        echo ""$TEMP "°C"
        echo "#F2777A"
        if [[ $BLOCK_BUTTON == '1' ]]; then
                urxvt -title "float" -geometry 80x12 -hold -e acpi -t
        fi
fi

