#!/bin/bash

ICON=""

DB_STATUS=$(dropbox status)
ERROR_COLOR=`cat ~/.colors | grep base08 | cut -d = -f 2`
SYNCING_COLOR=`cat ~/.colors | grep base0E | cut -d = -f 2`

if [[ $LANG == "de_DE.UTF-8" ]]; then
        if [[ $(echo $DB_STATUS | grep -Fo 'Aktualisiert') ]]; then
                COLOR=""
        elif [[ $(echo $DB_STATUS | grep -Fo 'Uploading') ]]; then
                COLOR=`echo $SYNCING_COLOR`
        elif [[ $(echo $DB_STATUS | grep -Fo 'Synchronisieren') ]]; then
                COLOR=`echo $SYNCING_COLOR`
        elif [[ $(echo $DB_STATUS | grep -Fo 'Downloading') ]]; then
                COLOR=`echo $SYNCING_COLOR`
        elif [[ $(echo $DB_STATUS | grep -Fo "Starten") ]]; then
                COLOR=`echo $SYNCING_COLOR`
        elif [[ $(echo $DB_STATUS | grep -Fo "Index wird erstellt") ]]; then
                COLOR=`echo $SYNCING_COLOR`
        elif [[ $(echo $DB_STATUS | grep -Fo "Dropbox isn't running") ]]; then
                COLOR=`echo $ERROR_COLOR`
        fi
else
        if [[ $(echo $DB_STATUS | grep -Fo 'Up to date') ]]; then
                COLOR=""
        elif [[ $(echo $DB_STATUS | grep -Fo 'Uploading') ]]; then
                COLOR=`echo $SYNCING_COLOR`
        elif [[ $(echo $DB_STATUS | grep -Fo 'Syncing') ]]; then
                COLOR=`echo $SYNCING_COLOR`
        elif [[ $(echo $DB_STATUS | grep -Fo 'Downloading') ]]; then
                COLOR=`echo $SYNCING_COLOR`
        elif [[ $(echo $DB_STATUS | grep -Fo "Starting") ]]; then
                COLOR=`echo $SYNCING_COLOR`
        elif [[ $(echo $DB_STATUS | grep -Fo "Indexing") ]]; then
                COLOR=`echo $SYNCING_COLOR`
        elif [[ $(echo $DB_STATUS | grep -Fo "Dropbox isn't running") ]]; then
                COLOR=`echo $ERROR_COLOR`
        elif [[ $(echo $DB_STATUS | grep -Fo "Connecting") ]]; then
                COLOR=`echo $SYNCING_COLOR`
        fi
fi

# Click to see status:
if [[ $BLOCK_BUTTON == '3' ]]; then
        notify-send "`echo $(dropbox status)`" \
                -i /usr/share/icons/Numix-Circle/48/apps/Dropbox.svg
fi

echo $ICON
echo $ICON
echo $COLOR
