#!/bin/bash

BASE16_XRESOURCES_PATH=~/.config/base16-xresources/xresources

if [ $1 == "arc" ]; then
        sed -i ~/.i3/config -e 's/^set \$f_ws_fg.*$/set $f_ws_fg #ffffff/g'
        sed -i ~/.i3/config -e 's/^set \$f_ws_bg.*$/set $f_ws_bg #5294e2/g'
        sed -i ~/.i3/config -e 's/^set \$a_ws_fg.*$/set $a_ws_fg #323641/g'
        sed -i ~/.i3/config -e 's/^set \$a_ws_bg.*$/set $a_ws_bg #5294e2/g'
        sed -i ~/.i3/config -e 's/^set \$i_ws_fg.*$/set $i_ws_fg #323641/g'
        sed -i ~/.i3/config -e 's/^set \$i_ws_bg.*$/set $i_ws_bg #e7e8eb/g'
        sed -i ~/.i3/config -e 's/^set \$u_ws_fg.*$/set $u_ws_fg #323641/g'
        sed -i ~/.i3/config -e 's/^set \$u_ws_bg.*$/set $u_ws_bg #dc322f/g'
        sed -i ~/.i3/config -e 's/^set \$f_wd_fg.*$/set $f_wd_fg #ffffff/g'
        sed -i ~/.i3/config -e 's/^set \$f_wd_bg.*$/set $f_wd_bg #5294e2/g'
        sed -i ~/.i3/config -e 's/^set \$i_wd_fg.*$/set $i_wd_fg #323641/g'
        sed -i ~/.i3/config -e 's/^set \$i_wd_bg.*$/set $i_wd_bg #5294e2/g'
        sed -i ~/.i3/config -e 's/^set \$u_wd_fg.*$/set $u_wd_fg #323641/g'
        sed -i ~/.i3/config -e 's/^set \$u_wd_bg.*$/set $u_wd_bg #e7e8eb/g'
else
        filename=$BASE16_XRESOURCES_PATH/base16-$1-256.Xresources
        base00=`cat $filename | grep base00 | head -1 | cut -d ' ' -f 3`
        base01=`cat $filename | grep base01 | head -1 | cut -d ' ' -f 3`
        base02=`cat $filename | grep base02 | head -1 | cut -d ' ' -f 3`
        base03=`cat $filename | grep base03 | head -1 | cut -d ' ' -f 3`
        base04=`cat $filename | grep base04 | head -1 | cut -d ' ' -f 3`
        base05=`cat $filename | grep base05 | head -1 | cut -d ' ' -f 3`
        base06=`cat $filename | grep base06 | head -1 | cut -d ' ' -f 3`
        base07=`cat $filename | grep base07 | head -1 | cut -d ' ' -f 3`
        base08=`cat $filename | grep base08 | head -1 | cut -d ' ' -f 3`
        base09=`cat $filename | grep base09 | head -1 | cut -d ' ' -f 3`
        base0A=`cat $filename | grep base0A | head -1 | cut -d ' ' -f 3`
        base0B=`cat $filename | grep base0B | head -1 | cut -d ' ' -f 3`
        base0C=`cat $filename | grep base0C | head -1 | cut -d ' ' -f 3`
        base0D=`cat $filename | grep base0D | head -1 | cut -d ' ' -f 3`
        base0E=`cat $filename | grep base0E | head -1 | cut -d ' ' -f 3`
        base0F=`cat $filename | grep base0F | head -1 | cut -d ' ' -f 3`

        # Change the i3 colors:
        sed -i ~/.i3/config -e 's/^set \$f_ws_fg.*$/set $f_ws_fg '$base04'/g'
        sed -i ~/.i3/config -e 's/^set \$f_ws_bg.*$/set $f_ws_bg '$base02'/g'
        sed -i ~/.i3/config -e 's/^set \$a_ws_fg.*$/set $a_ws_fg '$base03'/g'
        sed -i ~/.i3/config -e 's/^set \$a_ws_bg.*$/set $a_ws_bg '$base02'/g'
        sed -i ~/.i3/config -e 's/^set \$i_ws_fg.*$/set $i_ws_fg '$base04'/g'
        sed -i ~/.i3/config -e 's/^set \$i_ws_bg.*$/set $i_ws_bg '$base00'/g'
        sed -i ~/.i3/config -e 's/^set \$u_ws_fg.*$/set $u_ws_fg #FFFFFF/g'
        sed -i ~/.i3/config -e 's/^set \$u_ws_bg.*$/set $u_ws_bg '$base08'/g'
        sed -i ~/.i3/config -e 's/^set \$f_wd_fg.*$/set $f_wd_fg '$base04'/g'
        sed -i ~/.i3/config -e 's/^set \$f_wd_bg.*$/set $f_wd_bg '$base02'/g'
        sed -i ~/.i3/config -e 's/^set \$i_wd_fg.*$/set $i_wd_fg '$base04'/g'
        sed -i ~/.i3/config -e 's/^set \$i_wd_bg.*$/set $i_wd_bg '$base00'/g'
        sed -i ~/.i3/config -e 's/^set \$u_wd_fg.*$/set $u_wd_fg '$base04'/g'
        sed -i ~/.i3/config -e 's/^set \$u_wd_bg.*$/set $u_wd_bg '$base00'/g'
fi

i3-msg reload
nohup python3 ~/.i3/scripts/autoname-workspaces.py > /dev/null &
