#!/bin/bash

# sed -i ~/.i3/config -e 's/Material Design Icons 13/Material Design Icons 16/g'
# i3-msg reload

gsettings set org.gnome.desktop.wm.preferences titlebar-font \
        'Futura Bk BT Book 16'

gsettings set org.gnome.desktop.interface font-name \
        'Futura Bk BT Book 16'

gsettings set org.gnome.desktop.interface document-font-name \
        'Futura Bk BT Book 16'

gsettings set org.gnome.desktop.interface monospace-font-name \
        'Inconsolata Medium 16'

XDEFAULTS=~/Dropbox/dotfiles/.Xdefaults
sed -i $XDEFAULTS -e '6,9s/^/!/g' -e '10,13s/!//g' \
        && xrdb -load $XDEFAULTS
