#!/bin/bash

# Change urxvt colorscheme:
sed -i ~/Dropbox/dotfiles/.Xdefaults -e '52,107s/^!#/#/g' -e '52,107s/^!\*/*/g' \
        -e '113,168s/^#/!#/g' -e '113,168s/^\*/!*/g'
sed -i ~/Dropbox/dotfiles/.Xdefaults -e 's/URxvt\.background/!URxvt.background/g'

xrdb -load ~/Dropbox/dotfiles/.Xdefaults

# Change powerline prompt:
sed -i ~/Dropbox/dotfiles/.zshrc -e 's/powerline-prompt-dark/powerline-prompt/g'


# Change vim colorscheme:
sed -i ~/Dropbox/dotfiles/.vimrc -e 's/set bg=dark/set bg=light/g'

# Change i3 colors:
sed -i ~/.i3/config -e 's/set \$foreground #657b83/set \$foreground #323641/g'
sed -i ~/.i3/config -e 's/set \$background #002b36/set \$background #e1e4e7/g'
sed -i ~/.i3/config -e 's/set \$selected #268bd2/set \$selected #5294e2/g'
sed -i ~/.i3/config -e 's/set \$text #93a1a1/set \$text #525d76/g'
sed -i ~/.i3/config -e 's/set \$grey #586e75/set \$grey #9299a4/g'
i3-msg reload

# Change gtk theme:
gsettings set org.gnome.desktop.interface gtk-theme "Arc"
gsettings set org.gnome.desktop.wm.preferences "Arc"
sed -i ~/.config/gtk-3.0/settings.ini -e \
        's/gtk-application-prefer-dark-theme=1/gtk-application-prefer-dark-theme=0/g'

