#!/bin/bash

# If free memory is lower than a cutoff, show it in the status bar.
MEMORY_WARNING_CUTOFF=20
COLOR=`cat ~/.colors | grep base0F | cut -d = -f 2`

if [[ $LANG == "de_DE.utf8" ]] | [[ $LANG == "de_DE.UTF-8" ]] ; then
        MEMORY=$(free -h G | awk '{ print $7}' | sed -n '2p' | \
                grep -oP '\d+,\d+')
        MEMORY=`echo $MEMORY | sed -e 's/,//g'`
else
        MEMORY=$(free -h G | awk '{ print $7}' | sed -n '2p' | \
                grep -oP '\d+.\d+')
        MEMORY=`echo $MEMORY "* 10" | bc -l | cut -d "." -f 1`
fi

if [[ $((MEMORY)) -lt $((MEMORY_WARNING_CUTOFF)) ]]; then
        if [[ $LANG == "de_DE.utf8" ]] | [[ $LANG == "de_DE.UTF-8" ]] ; then
                MEMORY=`echo $MEMORY "/ 10" | bc -l | \
                        awk '{printf "%,1f\n", $0}'`
        else
                MEMORY=`echo $MEMORY "/ 10" | bc -l | \
                        awk '{printf "%.1f\n", $0}'`
        fi
        echo "-RAM:" $MEMORY"G"
        echo "-RAM:" $MEMORY"G"
        echo $COLOR
        if [[ $BLOCK_BUTTON == '3' ]]; then
                notify-send "`echo Free RAM: "$MEMORY"G`"
        fi
fi
