#!/bin/bash

# If free memory is lower than a cutoff, show it in the status bar.
MEMORY_WARNING_CUTOFF=10
MEMORY=$(free -h G | awk '{ print $4}' | sed -n '3p' | grep -oP '\d+.\d+')
MEMORY=`echo $MEMORY "* 10" | bc -l | cut -d "." -f 1`

if [[ $((MEMORY)) -lt $((MEMORY_WARNING_CUTOFF)) ]]; then
        MEMORY=`echo $MEMORY "/ 10" | bc -l |  awk '{printf "%.1f\n", $0}'`
        echo "-RAM:" $MEMORY"G"
        echo "-RAM:" $MEMORY"G"
        echo "#F2777A"
        if [[ $BLOCK_BUTTON == '1' ]]; then
                urxvt -title "float" -geometry 80x20 -hold -e htop
        fi
fi

