#!/bin/bash

sed -i ~/.i3/config -e 's/Material Design Icons 18/Material Design Icons 14/g'
i3-msg reload

gsettings set org.gnome.desktop.wm.preferences titlebar-font \
        'Fira Sans Semi-Light 11'

gsettings set org.gnome.desktop.interface font-name \
        'Fira Sans Semi-Light 11'

gsettings set org.gnome.desktop.interface document-font-name \
        'Fira Sans Semi-Light 11'

gsettings set org.gnome.desktop.interface monospace-font-name \
        'Inconsolata Medium 11'

XDEFAULTS=~/Dropbox/dotfiles/.Xdefaults
sed -i $XDEFAULTS -e '6,9s/!//g' -e '10,13s/^/!/g' \
        && xrdb -load $XDEFAULTS
