#!/bin/bash

XDEFAULTS=~/Dropbox/dotfiles/.Xdefaults

# Change urxvt colorscheme:
sed -i $XDEFAULTS -e '52,107s/^#/!#/g' -e '52,107s/^\*/!*/g' \
        -e '113,168s/^!#/#/g' -e '113,168s/^!\*/*/g'
sed -i $XDEFAULTS -e 's/!URxvt\.background/URxvt.background/g'
xrdb -load $XDEFAULTS

# Change powerline prompt:
sed -i ~/Dropbox/dotfiles/.zshrc -e 's/powerline-prompt$/powerline-prompt-dark/g'

# Change vim colorscheme:
sed -i ~/Dropbox/dotfiles/.vimrc -e 's/set bg=light/set bg=dark/g'

# Change i3 colors:
sed -i ~/.i3/config -e 's/set \$foreground #323641/set \$foreground #657b83/g'
sed -i ~/.i3/config -e 's/set \$background #e1e4e7/set \$background #002b36/g'
sed -i ~/.i3/config -e 's/set \$selected #5294e2/set \$selected #268bd2/g'
sed -i ~/.i3/config -e 's/set \$text #525d76/set \$text #93a1a1/g'
sed -i ~/.i3/config -e 's/set \$grey #9299a4/set \$grey #586e75/g'
i3-msg reload

# Change gtk theme:
gsettings set org.gnome.desktop.interface gtk-theme "Arc-Darker"
gsettings set org.gnome.desktop.wm.preferences "Arc-Darker"
sed -i ~/.config/gtk-3.0/settings.ini -e \
        's/gtk-application-prefer-dark-theme=0/gtk-application-prefer-dark-theme=1/g'
