#!/bin/bash

# Directory of wallpapers:
DIR="$HOME/Dropbox/wallpapers/"

# Choose a random wallpaper from files in that directory:
FILES=($DIR/*)
WALLPAPER=`printf "%s\n" "${FILES[RANDOM % ${#FILES[@]}]}"`

# Set as desktop background:
feh --bg-scale "$WALLPAPER"
