#!/bin/bash

# Change urxvt colorscheme:
cp ~/Dropbox/dotfiles/.Xdefaults-solarized-dark ~/Dropbox/dotfiles/.Xdefaults
xrdb -load ~/Dropbox/dotfiles/.Xdefaults

# Change powerline prompt:
sed -i ~/Dropbox/dotfiles/.zshrc -e \
        's/powerline-prompt.*$/powerline-prompt-solarized-dark/g'

# Change vim colorscheme:
sed -i ~/Dropbox/dotfiles/.vimrc -e 's/set bg=light/set bg=dark/g'
sed -i ~/Dropbox/dotfiles/.vimrc -e 's/" hi normal ctermbg/hi normal ctermbg/g'
sed -i ~/Dropbox/dotfiles/.vimrc -e \
        's/^let g:airline_theme.*$/let g:airline_theme = "solarized"/g'

# Make i3bar transparent:
sed -i ~/.i3/compton -e 's/dock = { opacity.*$/dock = { opacity = 0.95; };/g'
killall compton
compton -b --conf ~/.i3/compton

# Change i3 colors:
sed -i ~/.i3/config -e 's/set \$foreground.*$/set \$foreground #657b83/g'
sed -i ~/.i3/config -e 's/set \$background.*$/set \$background #002b36/g'
sed -i ~/.i3/config -e 's/set \$selected.*$/set \$selected #268bd2/g'
sed -i ~/.i3/config -e 's/set \$text.*$/set \$text #93a1a1/g'
sed -i ~/.i3/config -e 's/set \$grey.*$/set \$grey #586e75/g'
i3-msg reload

# Change gtk theme:
gsettings set org.gnome.desktop.interface gtk-theme "Arc-Darker"
gsettings set org.gnome.desktop.wm.preferences "Arc-Darker"
sed -i ~/.config/gtk-3.0/settings.ini -e \
        's/gtk-application-prefer-dark-theme=0/gtk-application-prefer-dark-theme=1/g'

nohup python3 ~/.i3/scripts/autoname-workspaces.py > /dev/null &
