#!/bin/bash

# Change urxvt colorscheme:
cp ~/Dropbox/dotfiles/.Xdefaults-solarized-light ~/Dropbox/dotfiles/.Xdefaults
xrdb -load ~/Dropbox/dotfiles/.Xdefaults

# Change powerline prompt:
sed -i ~/Dropbox/dotfiles/.zshrc -e \
        's/powerline-prompt.*$/powerline-prompt-solarized-light/g'

# Change vim colorscheme:
sed -i ~/Dropbox/dotfiles/.vimrc -e 's/^colorscheme.*$/colorscheme solarized/g'
sed -i ~/Dropbox/dotfiles/.vimrc -e 's/set bg=dark/set bg=light/g'
sed -i ~/Dropbox/dotfiles/.vimrc -e 's/^hi normal ctermbg/" hi normal ctermbg/g'
sed -i ~/Dropbox/dotfiles/.vimrc -e \
        's/^let g:airline_theme.*$/let g:airline_theme = "solarized"/g'

# Make i3bar not transparent:
sed -i ~/.i3/compton -e 's/dock = { opacity.*$/dock = { opacity = 1.00; };/g'
killall compton
compton -b --conf ~/.i3/compton

# Change R colors:
sed -i ~/Dropbox/dotfiles/.Rprofile -e \
        's/^.*Set colorscheme/  solarizedLight()  # Set colorscheme/g'

# Change i3 colors:
sed -i ~/.i3/config -e 's/^set \$f_ws_fg.*$/set $f_ws_fg #ffffff/g'
sed -i ~/.i3/config -e 's/^set \$f_ws_bg.*$/set $f_ws_bg #5294e2/g'
sed -i ~/.i3/config -e 's/^set \$a_ws_fg.*$/set $a_ws_fg #323641/g'
sed -i ~/.i3/config -e 's/^set \$a_ws_bg.*$/set $a_ws_bg #5294e2/g'
sed -i ~/.i3/config -e 's/^set \$i_ws_fg.*$/set $i_ws_fg #323641/g'
sed -i ~/.i3/config -e 's/^set \$i_ws_bg.*$/set $i_ws_bg #e7e8eb/g'
sed -i ~/.i3/config -e 's/^set \$u_ws_fg.*$/set $u_ws_fg #323641/g'
sed -i ~/.i3/config -e 's/^set \$u_ws_bg.*$/set $u_ws_bg #dc322f/g'
sed -i ~/.i3/config -e 's/^set \$f_wd_fg.*$/set $f_wd_fg #ffffff/g'
sed -i ~/.i3/config -e 's/^set \$f_wd_bg.*$/set $f_wd_bg #5294e2/g'
sed -i ~/.i3/config -e 's/^set \$i_wd_fg.*$/set $i_wd_fg #323641/g'
sed -i ~/.i3/config -e 's/^set \$i_wd_bg.*$/set $i_wd_bg #5294e2/g'
sed -i ~/.i3/config -e 's/^set \$u_wd_fg.*$/set $u_wd_fg #323641/g'
sed -i ~/.i3/config -e 's/^set \$u_wd_bg.*$/set $u_wd_bg #e7e8eb/g'
i3-msg reload

# Change gtk theme:
gsettings set org.gnome.desktop.interface gtk-theme "Arc"
gsettings set org.gnome.desktop.wm.preferences "Arc"
sed -i ~/.config/gtk-3.0/settings.ini -e \
        's/gtk-application-prefer-dark-theme=1/gtk-application-prefer-dark-theme=0/g'

nohup python3 ~/.i3/scripts/autoname-workspaces.py > /dev/null &
