#!/bin/bash

# Add a button to toggle play and pause on Spotify if it's running
if [[ $(ps -U root -u root -N | grep -Fo 'spotify') == *spotify* ]]; then
        STATUS=`playerctl -p spotify status`
        # Change the symbol based on if it's currently playing or paused:
        if [[ $STATUS == 'Paused' ]]; then
                echo ""
        elif [[ $STATUS == 'Playing' ]]; then
                echo ""
        # If for some reason this doesn't work, just display the play/pause symbol:
        else
                echo ""
        fi
        if [[ $BLOCK_BUTTON == '1' ]]; then
                playerctl -p spotify play-pause
        fi
# Sometimes I use Rhythmbox:
elif [[ $(ps -U root -u root -N | grep -Fo 'rhythmbox') == *rhythmbox* ]]; then
        STATUS=`playerctl -p rhythmbox status`
        # Change the symbol based on if it's currently playing or paused:
        if [[ $STATUS == 'Paused' ]]; then
                echo ""
        elif [[ $STATUS == 'Playing' ]]; then
                echo ""
        # If for some reason this doesn't work, just display the play/pause symbol:
        else
                echo ""
        fi
        if [[ $BLOCK_BUTTON == '1' ]]; then
                playerctl -p rhythmbox play-pause
        fi
else
        exit 0
fi
