#!/bin/bash

# Change urxvt colorscheme:
cp ~/Dropbox/dotfiles/.Xdefaults-tomorrow-night-eighties \
        ~/Dropbox/dotfiles/.Xdefaults
xrdb -load ~/Dropbox/dotfiles/.Xdefaults

# Change powerline prompt:
sed -i ~/Dropbox/dotfiles/.zshrc -e 's/powerline-prompt.*$/powerline-prompt-tne/g'

# Change vim colorscheme:
sed -i ~/Dropbox/dotfiles/.vimrc -e \
        's/^colorscheme.*$/colorscheme Tomorrow-Night-Eighties/g'
sed -i ~/Dropbox/dotfiles/.vimrc -e \
        's/^let g:airline_theme.*$/let g:airline_theme = "wombat"/g'
sed -i ~/Dropbox/dotfiles/.vimrc -e 's/set bg=light/set bg=dark/g'
sed -i ~/Dropbox/dotfiles/.vimrc -e 's/" hi normal ctermbg/hi normal ctermbg/g'

# Make i3bar transparent:
sed -i ~/.i3/compton -e 's/dock = { opacity.*$/dock = { opacity = 0.85; };/g'
killall compton
compton -b --conf ~/.i3/compton

# Change R colors:
sed -i ~/Dropbox/dotfiles/.Rprofile -e \
        's/^.*Set colorscheme/  tomorrowNightEighties()  # Set colorscheme/g'

# Change i3 colors:
sed -i ~/.i3/config -e 's/^set \$f_ws_fg.*$/set $f_ws_fg #2d2d2d/g'
sed -i ~/.i3/config -e 's/^set \$f_ws_bg.*$/set $f_ws_bg #cccccc/g'
sed -i ~/.i3/config -e 's/^set \$a_ws_fg.*$/set $a_ws_fg #2d2d2d/g'
sed -i ~/.i3/config -e 's/^set \$a_ws_bg.*$/set $a_ws_bg #999999/g'
sed -i ~/.i3/config -e 's/^set \$i_ws_fg.*$/set $i_ws_fg #cccccc/g'
sed -i ~/.i3/config -e 's/^set \$i_ws_bg.*$/set $i_ws_bg #2d2d2d/g'
sed -i ~/.i3/config -e 's/^set \$u_ws_fg.*$/set $u_ws_fg #2d2d2d/g'
sed -i ~/.i3/config -e 's/^set \$u_ws_bg.*$/set $u_ws_bg #f2777a/g'
sed -i ~/.i3/config -e 's/^set \$f_wd_fg.*$/set $f_wd_fg #2d2d2d/g'
sed -i ~/.i3/config -e 's/^set \$f_wd_bg.*$/set $f_wd_bg #cccccc/g'
sed -i ~/.i3/config -e 's/^set \$i_wd_fg.*$/set $i_wd_fg #cccccc/g'
sed -i ~/.i3/config -e 's/^set \$i_wd_bg.*$/set $i_wd_bg #999999/g'
sed -i ~/.i3/config -e 's/^set \$u_wd_fg.*$/set $u_wd_fg #cccccc/g'
sed -i ~/.i3/config -e 's/^set \$u_wd_bg.*$/set $u_wd_bg #2d2d2d/g'
i3-msg reload

# Change gtk theme:
gsettings set org.gnome.desktop.interface gtk-theme "Arc"
gsettings set org.gnome.desktop.wm.preferences "Arc"
sed -i ~/.config/gtk-3.0/settings.ini -e \
        's/gtk-application-prefer-dark-theme=1/gtk-application-prefer-dark-theme=0/g'

nohup python3 ~/.i3/scripts/autoname-workspaces.py > /dev/null &
