#!/bin/bash

# Script to create pop-up notification when volume changes.

# Create a delay so the change in volume can be registered:
sleep 0.05

# Get the volume and check if muted or not (STATE):
VOLUME=$(amixer sget Master      | \
         egrep -o -m 1 "[0-9]+%" | \
         egrep -o "[0-9]+")
STATE=`amixer sget Master          | \
       egrep -m 1 'Playback.*?\[o' | \
       egrep -o '\[o.+\]'`

# To avoid many notifications piling on top of eachother when pressing the
# volume buttons multiple times, kill the notification daemon each time.
NOTIFD=`cat /usr/share/dbus-1/services/org.freedesktop.Notifications.service | grep Exec | cut -d = -f 2`
killall -q $NOTIFD

if [[ $LANG == "de_DE.UTF-8" ]]; then
        MUTE="Stumm"
        VOL="Lautstärke"
elif [[ $LANG == "ga_IE.UTF-8" ]]; then
        MUTE="Gan Fuaim"
        VOL="Airde"
else
        MUTE="Mute"
        VOL="Volume"
fi

# Have a different symbol for varying volume levels:
if [[ $STATE != '[off]' ]]; then
        if [ $VOLUME == "0" ]; then
                notify-send "$VOL: $VOLUME" -t 1000 -i ~/.i3/icons/vol-mute.png
        elif [ $VOLUME -lt "33" ] && [ $VOLUME -gt "0" ]; then
                notify-send "$VOL: $VOLUME" -t 1000 -i ~/.i3/icons/vol-low.png
        elif [ $VOLUME -lt "67" ] && [ $VOLUME -ge "33" ]; then
                notify-send "$VOL: $VOLUME" -t 1000 -i ~/.i3/icons/vol-med.png
        else
                notify-send "$VOL: $VOLUME" -t 1000 -i ~/.i3/icons/vol-high.png
        fi
# If volume is muted, display the mute sybol:
else
        notify-send "$MUTE" -t 1000  -i ~/.i3/icons/vol-mute.png
fi
