#!/bin/bash
python3 ~/.i3/scripts/weather-short.py
if [[ $BLOCK_BUTTON == '3' ]]; then
        WEATHER=$(python3 ~/.i3/scripts/weather-long.py)
        notify-send "$(echo $WEATHER)" -t 10000 -i \
                /usr/share/icons/Numix-Circle/scalable/apps/indicator-weather.svg
fi


